"""GitAnalyzer — inspects repository git state."""
from __future__ import annotations

import subprocess
import time

from doctor.base import BaseAnalyzer
from doctor.finding import Finding, Severity
from doctor.result import AnalyzerResult

_CATEGORY = "git"


class GitAnalyzer(BaseAnalyzer):
    """Checks: repo presence, branch, dirty tree, recent commit history."""

    NAME = "git"

    def analyze(self) -> AnalyzerResult:
        start = time.monotonic()
        findings: list[Finding] = []

        if not (self._root / ".git").exists():
            findings.append(Finding(
                category=_CATEGORY,
                severity=Severity.CRITICAL,
                title="Not a git repository",
                detail=f"{self._root} contains no .git directory.",
                recommendation="Run `git init` to initialise version control.",
            ))
            return _result(findings, start)

        # Branch
        branch = self._git("rev-parse", "--abbrev-ref", "HEAD")
        if branch:
            findings.append(Finding(
                category=_CATEGORY,
                severity=Severity.INFO,
                title=f"Current branch: {branch}",
                data={"branch": branch},
            ))

        # Dirty working tree, split by what the dirtiness actually is.
        #
        # A single undifferentiated count made MondayOS fail itself: every agent
        # run wrote a generated research record and bumped a sequence counter,
        # which this analyzer reported as "uncommitted changes", Advise escalated
        # to a HIGH engineering risk, and the planner fed back into the next
        # run's prompt as repository state. QA then failed the task for the mess
        # its own pipeline had just made — and each rerun made the number worse.
        # Runtime state is not source entanglement, and is reported separately.
        porcelain = self._git("status", "--porcelain")
        if porcelain:
            changed = [ln for ln in porcelain.splitlines() if ln.strip()]
            source, runtime = _split_source_and_runtime(changed)

            if source:
                findings.append(Finding(
                    category=_CATEGORY,
                    severity=Severity.WARNING,
                    title=f"Dirty working tree — {len(source)} uncommitted source change(s)",
                    detail="\n".join(source[:15]),
                    recommendation="Commit or stash source changes before deployment.",
                    data={"changed_files": len(source), "source_changes": len(source)},
                ))
            else:
                findings.append(Finding(
                    category=_CATEGORY,
                    severity=Severity.OK,
                    title="Source working tree is clean",
                    data={"changed_files": 0, "source_changes": 0},
                ))

            if runtime:
                findings.append(Finding(
                    category=_CATEGORY,
                    severity=Severity.INFO,
                    title=f"{len(runtime)} runtime-state change(s) (not source)",
                    detail=_describe_runtime(runtime),
                    recommendation=(
                        "Generated by MondayOS itself — knowledge captures, sequence "
                        "counters, run logs. Not a delivery risk."
                    ),
                    data={"runtime_changes": len(runtime)},
                ))
        else:
            findings.append(Finding(
                category=_CATEGORY,
                severity=Severity.OK,
                title="Working tree is clean",
                data={"changed_files": 0, "source_changes": 0},
            ))

        # Recent commits
        log = self._git("log", "--oneline", "-10")
        if log:
            commits = log.splitlines()
            findings.append(Finding(
                category=_CATEGORY,
                severity=Severity.INFO,
                title=f"{len(commits)} recent commit(s)",
                detail="\n".join(commits),
                data={"recent_commits": commits},
            ))
        else:
            findings.append(Finding(
                category=_CATEGORY,
                severity=Severity.WARNING,
                title="No commits found",
                recommendation="Make an initial commit to begin tracking history.",
            ))

        # Unpushed commits (best-effort — may fail if no remote)
        unpushed = self._git("log", "@{u}..", "--oneline")
        if unpushed:
            n = len(unpushed.splitlines())
            findings.append(Finding(
                category=_CATEGORY,
                severity=Severity.INFO,
                title=f"{n} unpushed commit(s) ahead of upstream",
                detail=unpushed,
                recommendation="Run `git push` to sync with remote.",
                data={"unpushed": n},
            ))

        return _result(findings, start)

    def _git(self, *args: str) -> str:
        try:
            r = subprocess.run(
                ["git", "-C", str(self._root), *args],
                capture_output=True, text=True, timeout=10,
            )
            return r.stdout.strip()
        except (subprocess.TimeoutExpired, FileNotFoundError, OSError):
            return ""


# Paths that are MondayOS's own runtime output rather than source code.
# Deliberately narrow: anything not matched here counts as source, so a genuine
# change is never quietly reclassified as harmless runtime noise.
_RUNTIME_PREFIXES: tuple[str, ...] = (
    "knowledge/runtime/",   # generated knowledge captures
    "logs/",                # agent, team, execution and publish run records
)
_RUNTIME_SUFFIXES: tuple[str, ...] = (
    ".sequences.json",      # knowledge/task ID counters
)


def _porcelain_path(line: str) -> str:
    """Extract the path from a `git status --porcelain` line, rename-aware."""
    path = line[3:] if len(line) > 3 else ""
    if " -> " in path:                      # "R  old -> new"
        path = path.split(" -> ", 1)[1]
    return path.strip().strip('"')


def _is_runtime(path: str) -> bool:
    return (
        path.startswith(_RUNTIME_PREFIXES)
        or path.endswith(_RUNTIME_SUFFIXES)
    )


def _split_source_and_runtime(changed: list[str]) -> tuple[list[str], list[str]]:
    source, runtime = [], []
    for line in changed:
        (runtime if _is_runtime(_porcelain_path(line)) else source).append(line)
    return source, runtime


def _describe_runtime(runtime: list[str]) -> str:
    """Group runtime changes so humans and agents read intent, not a file list."""
    generated = sum(1 for ln in runtime if _porcelain_path(ln).startswith("knowledge/runtime/"))
    counters = sum(1 for ln in runtime if _porcelain_path(ln).endswith(".sequences.json"))
    logs = sum(1 for ln in runtime if _porcelain_path(ln).startswith("logs/"))

    parts = []
    if generated:
        parts.append(f"{generated} generated knowledge record(s)")
    if counters:
        parts.append(f"{counters} sequence counter(s) changed")
    if logs:
        parts.append(f"{logs} agent/team run log(s)")
    return "\n".join(parts)


def _result(findings: list[Finding], start: float) -> AnalyzerResult:
    return AnalyzerResult(
        name=GitAnalyzer.NAME,
        findings=findings,
        duration_ms=(time.monotonic() - start) * 1000,
    )
